// Code generated by const-gen. DO NOT EDIT.
// Source: templates.yaml

package subdomain_discovery

// Stage name constants (auto-generated from templates.yaml)
const (
	stageRecon = "recon"
	stageBruteforce = "bruteforce"
	stagePermutation = "permutation"
	stageResolve = "resolve"
)

// Tool name constants (auto-generated from templates.yaml)
const (
	toolSublist3r = "sublist3r"
	toolAssetfinder = "assetfinder"
	toolSubdomainBruteforce = "subdomain-bruteforce"
	toolSubdomainResolve = "subdomain-resolve"
	toolSubdomainPermutationResolve = "subdomain-permutation-resolve"
	toolSubfinder = "subfinder"
)
