#!/usr/bin/env bash

lf_ui_print_install_summary() {
  local image_tag="$1"
  local compose_file="$2"

  echo ""
  success_animation "安装完成!"

  echo ""
  echo -e "${BOLD}${CYAN}🌐 访问地址:${RESET} ${UNDERLINE}https://localhost:8083/${RESET}"
  echo -e "${BOLD}${MAGENTA}🧰 默认账号:${RESET} ${BOLD}admin${RESET}"
  echo -e "${BOLD}${MAGENTA}🔐 默认密码:${RESET} ${BOLD}admin${RESET}"
  echo ""
  echo -e "${BOLD}${YELLOW}🐳 镜像说明:${RESET}"
  echo -e "   ${DIM}服务镜像:${RESET} ${GREEN}yyhuni/lunafox-server:${image_tag}${RESET}"
  echo -e "   ${DIM}前端镜像:${RESET} ${GREEN}yyhuni/lunafox-frontend:${image_tag}${RESET}"
  echo -e "   ${DIM}网关镜像:${RESET} ${GREEN}yyhuni/lunafox-nginx:${image_tag}${RESET}"
  echo -e "   ${DIM}Agent 镜像:${RESET} ${GREEN}yyhuni/lunafox-agent:${image_tag}${RESET}"
  echo -e "   ${DIM}Worker 镜像:${RESET} ${GREEN}yyhuni/lunafox-worker:${image_tag}${RESET}"
  echo ""
  echo -e "${BOLD}${YELLOW}📋 常用命令:${RESET}"
  echo -e "   ${DIM}停止服务:${RESET} ./stop.sh"
  echo -e "   ${DIM}重启服务:${RESET} ./restart.sh"
  echo -e "   ${DIM}启动服务:${RESET} ./start.sh"
  echo ""
  echo -e "${BOLD}${YELLOW}📦 日志/镜像:${RESET}"
  echo -e "   ${DIM}查看日志(全部):${RESET} ${COMPOSE_CMD[*]} -f ${compose_file} logs -f"
  echo -e "   ${DIM}查看日志(后端):${RESET} ${COMPOSE_CMD[*]} -f ${compose_file} logs -f server"
  echo -e "   ${DIM}查看日志(前端):${RESET} ${COMPOSE_CMD[*]} -f ${compose_file} logs -f frontend"
  echo -e "   ${DIM}查看日志(网关):${RESET} ${COMPOSE_CMD[*]} -f ${compose_file} logs -f nginx"
  echo -e "   ${DIM}查看日志(数据库):${RESET} ${COMPOSE_CMD[*]} -f ${compose_file} logs -f postgres"
  echo -e "   ${DIM}查看日志(Redis):${RESET} ${COMPOSE_CMD[*]} -f ${compose_file} logs -f redis"
  echo -e "   ${DIM}查看日志(Agent):${RESET} docker logs -f lunafox-agent"
  echo -e "   ${DIM}查看镜像:${RESET} docker images | grep lunafox"
  echo ""
}
