model_provider = "custom"
model = "gpt-5.2-codex"
model_reasoning_effort = "high"
disable_response_storage = true

[model_providers.custom]
name = "custom"
base_url = "https://www.cursorhub.cloud/openai"
wire_api = "responses"
requires_openai_auth = true

[projects."/Users/yangyang/Desktop/orbit"]
trust_level = "trusted"
