package main

import (
	"flag"
	"fmt"
	"math/rand"
	"os"
	"time"

	"github.com/lib/pq"
	"github.com/xingrin/go-backend/internal/config"
	"github.com/xingrin/go-backend/internal/database"
	"github.com/xingrin/go-backend/internal/model"
	"gorm.io/gorm"
)

var (
	clear    = flag.Bool("clear", false, "Clear existing data before generating")
	orgCount = flag.Int("orgs", 20, "Number of organizations to generate")
	// targetCount = orgCount * 20, websiteCount = targetCount * 20
)

func main() {
	flag.Parse()

	// Calculate counts based on org count
	// Each org has 20 targets, each target has 20 websites/endpoints/directories
	// Subdomains only for domain-type targets
	targetsPerOrg := 20
	assetsPerTarget := 20
	targetCount := *orgCount * targetsPerOrg

	// Load config
	cfg, err := config.Load()
	if err != nil {
		fmt.Printf("❌ Failed to load config: %v\n", err)
		os.Exit(1)
	}

	// Connect to database
	db, err := database.NewDatabase(&cfg.Database)
	if err != nil {
		fmt.Printf("❌ Failed to connect to database: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("🚀 Starting test data generation...")
	fmt.Printf("   Organizations: %d\n", *orgCount)
	fmt.Printf("   Targets: %d (%d per org)\n", targetCount, targetsPerOrg)
	fmt.Printf("   Assets per target: %d (websites, endpoints, directories, subdomains for domains)\n", assetsPerTarget)
	fmt.Println()

	if *clear {
		fmt.Println("🗑️  Clearing existing data...")
		if err := clearData(db); err != nil {
			fmt.Printf("❌ Failed to clear data: %v\n", err)
			os.Exit(1)
		}
		fmt.Println("   ✓ Data cleared")
	}

	// Generate data
	orgIDs, err := createOrganizations(db, *orgCount)
	if err != nil {
		fmt.Printf("❌ Failed to create organizations: %v\n", err)
		os.Exit(1)
	}

	targets, err := createTargets(db, targetCount)
	if err != nil {
		fmt.Printf("❌ Failed to create targets: %v\n", err)
		os.Exit(1)
	}

	// Extract target IDs
	targetIDs := make([]int, len(targets))
	for i, t := range targets {
		targetIDs[i] = t.ID
	}

	// Link targets to organizations (20 per org)
	if err := linkTargetsToOrganizations(db, targetIDs, orgIDs); err != nil {
		fmt.Printf("❌ Failed to link targets to organizations: %v\n", err)
		os.Exit(1)
	}

	// Create websites for targets (20 per target)
	if err := createWebsites(db, targets, assetsPerTarget); err != nil {
		fmt.Printf("❌ Failed to create websites: %v\n", err)
		os.Exit(1)
	}

	// Create subdomains for domain-type targets only (20 per target)
	if err := createSubdomains(db, targets, assetsPerTarget); err != nil {
		fmt.Printf("❌ Failed to create subdomains: %v\n", err)
		os.Exit(1)
	}

	// Create endpoints for targets (20 per target)
	if err := createEndpoints(db, targets, assetsPerTarget); err != nil {
		fmt.Printf("❌ Failed to create endpoints: %v\n", err)
		os.Exit(1)
	}

	// Create directories for targets (20 per target)
	if err := createDirectories(db, targets, assetsPerTarget); err != nil {
		fmt.Printf("❌ Failed to create directories: %v\n", err)
		os.Exit(1)
	}

	// Create host port mappings for targets (20 per target)
	if err := createHostPortMappings(db, targets, assetsPerTarget); err != nil {
		fmt.Printf("❌ Failed to create host port mappings: %v\n", err)
		os.Exit(1)
	}

	// Create screenshots for targets (no actual image data, just metadata)
	// Note: Real screenshots would be generated by scanners with actual WebP image data
	if err := createScreenshots(db, targets, 0); err != nil {
		fmt.Printf("❌ Failed to create screenshots: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("\n✅ Test data generation completed!")
}

func clearData(db *gorm.DB) error {
	// Delete in order to respect foreign key constraints
	tables := []string{
		"screenshot",
		"host_port_mapping",
		"directory",
		"endpoint",
		"subdomain",
		"website",
		"organization_target",
		"target",
		"organization",
	}

	for _, table := range tables {
		if err := db.Exec(fmt.Sprintf("DELETE FROM %s", table)).Error; err != nil {
			return fmt.Errorf("failed to clear %s: %w", table, err)
		}
	}
	return nil
}

func createOrganizations(db *gorm.DB, count int) ([]int, error) {
	fmt.Printf("🏢 Creating %d organizations...\n", count)

	orgNames := []string{
		"Acme Corporation", "TechStart Labs", "Global Finance", "HealthCare Plus",
		"E-Commerce Platform", "Smart City Systems", "Educational Tech", "Green Energy",
		"CyberSec Defense", "CloudNative Systems", "DataFlow Analytics", "MobileFirst Tech",
		"Quantum Research", "Autonomous Vehicles", "Biotech Innovations", "Space Technology",
		"AI Research Lab", "Blockchain Solutions", "IoT Platform", "DevOps Enterprise",
		"Security Operations", "Data Science Hub", "Machine Learning Co", "Network Solutions",
		"Infrastructure Corp", "Platform Services", "Digital Transformation", "Innovation Hub",
		"Tech Consulting", "Software Factory",
	}

	divisions := []string{
		"Global", "Asia Pacific", "EMEA", "Americas", "R&D", "Cloud Services",
		"Security Team", "Innovation Lab", "Enterprise", "Consumer Products",
	}

	descriptions := []string{
		"A leading technology company specializing in enterprise software solutions and cloud computing services.",
		"Innovative research lab focused on artificial intelligence and machine learning applications.",
		"Global financial services provider offering digital banking and payment solutions.",
		"Healthcare technology company developing electronic health records and telemedicine platforms.",
		"E-commerce platform serving millions of customers with B2B and B2C solutions.",
		"Smart city infrastructure provider specializing in IoT and urban management systems.",
		"Educational technology company providing online learning platforms and courses.",
		"Renewable energy management company focused on solar and wind power optimization.",
		"Cybersecurity firm offering penetration testing and security consulting services.",
		"Cloud-native systems developer specializing in Kubernetes and microservices.",
	}

	var ids []int
	suffix := rand.Intn(9000) + 1000

	for i := 0; i < count; i++ {
		name := fmt.Sprintf("%s - %s (%d-%d)",
			orgNames[i%len(orgNames)],
			divisions[rand.Intn(len(divisions))],
			suffix, i)

		desc := descriptions[rand.Intn(len(descriptions))]

		// Random created_at within last year
		daysAgo := rand.Intn(365)
		createdAt := time.Now().AddDate(0, 0, -daysAgo)

		org := &model.Organization{
			Name:        name,
			Description: desc,
			CreatedAt:   createdAt,
		}

		if err := db.Create(org).Error; err != nil {
			return nil, err
		}
		ids = append(ids, org.ID)
	}

	fmt.Printf("   ✓ Created %d organizations\n", len(ids))
	return ids, nil
}

func createTargets(db *gorm.DB, count int) ([]model.Target, error) {
	fmt.Printf("🎯 Creating %d targets...\n", count)

	// Domain templates
	envs := []string{"prod", "staging", "dev", "test", "api", "app", "www", "admin", "portal", "dashboard"}
	companies := []string{"acme", "techstart", "globalfinance", "healthcare", "ecommerce", "smartcity", "cybersec", "cloudnative", "dataflow", "mobilefirst"}
	tlds := []string{".com", ".io", ".net", ".org", ".dev", ".app", ".cloud", ".tech"}

	var targets []model.Target
	suffix := rand.Intn(9000) + 1000
	usedNames := make(map[string]bool)

	// Generate domains (70%)
	domainCount := count * 70 / 100
	for i := 0; i < domainCount; i++ {
		var name string
		for {
			env := envs[rand.Intn(len(envs))]
			company := companies[rand.Intn(len(companies))]
			tld := tlds[rand.Intn(len(tlds))]
			name = fmt.Sprintf("%s.%s-%d%s", env, company, suffix+i, tld)
			if !usedNames[name] {
				usedNames[name] = true
				break
			}
		}

		target := model.Target{
			Name:      name,
			Type:      "domain",
			CreatedAt: time.Now().AddDate(0, 0, -rand.Intn(365)),
		}

		if err := db.Create(&target).Error; err != nil {
			return nil, err
		}
		targets = append(targets, target)
	}

	// Generate IPs (20%)
	ipCount := count * 20 / 100
	for i := 0; i < ipCount; i++ {
		name := fmt.Sprintf("%d.%d.%d.%d",
			rand.Intn(223)+1,
			rand.Intn(256),
			rand.Intn(256),
			rand.Intn(254)+1)

		if usedNames[name] {
			continue
		}
		usedNames[name] = true

		target := model.Target{
			Name:      name,
			Type:      "ip",
			CreatedAt: time.Now().AddDate(0, 0, -rand.Intn(365)),
		}

		if err := db.Create(&target).Error; err != nil {
			return nil, err
		}
		targets = append(targets, target)
	}

	// Generate CIDRs (10%)
	cidrCount := count * 10 / 100
	for i := 0; i < cidrCount; i++ {
		masks := []int{8, 16, 24}
		mask := masks[rand.Intn(len(masks))]
		name := fmt.Sprintf("%d.%d.%d.0/%d",
			rand.Intn(223)+1,
			rand.Intn(256),
			rand.Intn(256),
			mask)

		if usedNames[name] {
			continue
		}
		usedNames[name] = true

		target := model.Target{
			Name:      name,
			Type:      "cidr",
			CreatedAt: time.Now().AddDate(0, 0, -rand.Intn(365)),
		}

		if err := db.Create(&target).Error; err != nil {
			return nil, err
		}
		targets = append(targets, target)
	}

	fmt.Printf("   ✓ Created %d targets (domains: %d, IPs: %d, CIDRs: %d)\n",
		len(targets), domainCount, ipCount, cidrCount)
	return targets, nil
}

func linkTargetsToOrganizations(db *gorm.DB, targetIDs, orgIDs []int) error {
	fmt.Println("🔗 Linking targets to organizations...")

	if len(orgIDs) == 0 || len(targetIDs) == 0 {
		return nil
	}

	// Each organization gets exactly 20 targets (evenly distributed)
	targetsPerOrg := len(targetIDs) / len(orgIDs)
	linkCount := 0

	for orgIdx, orgID := range orgIDs {
		startIdx := orgIdx * targetsPerOrg
		endIdx := startIdx + targetsPerOrg
		if orgIdx == len(orgIDs)-1 {
			endIdx = len(targetIDs) // Last org gets remaining targets
		}

		for i := startIdx; i < endIdx; i++ {
			err := db.Exec(
				"INSERT INTO organization_target (organization_id, target_id) VALUES (?, ?) ON CONFLICT DO NOTHING",
				orgID, targetIDs[i],
			).Error
			if err != nil {
				return err
			}
			linkCount++
		}
	}

	fmt.Printf("   ✓ Created %d target-organization links (%d per org)\n", linkCount, targetsPerOrg)
	return nil
}

func createWebsites(db *gorm.DB, targets []model.Target, websitesPerTarget int) error {
	totalCount := len(targets) * websitesPerTarget
	fmt.Printf("🌐 Creating %d websites (%d per target)...\n", totalCount, websitesPerTarget)

	if len(targets) == 0 {
		return nil
	}

	// Website data templates
	protocols := []string{"https://", "http://"}
	subdomains := []string{"www", "api", "app", "admin", "portal", "dashboard", "dev", "staging", "test", "cdn", "static", "assets", "mail", "blog", "docs", "support", "auth", "login", "shop", "store"}
	paths := []string{"", "/", "/api", "/v1", "/v2", "/login", "/dashboard", "/admin", "/app", "/docs"}
	ports := []string{"", ":8080", ":8443", ":3000", ":443"}

	titles := []string{
		"Welcome - Dashboard", "Admin Panel", "API Documentation", "Login Portal",
		"Home Page", "User Dashboard", "Settings", "Analytics", "Reports",
		"Management Console", "Control Panel", "Service Status", "Developer Portal",
	}

	webservers := []string{
		"nginx/1.24.0", "Apache/2.4.57", "cloudflare", "Microsoft-IIS/10.0",
		"nginx", "Apache", "LiteSpeed", "Caddy", "Traefik",
	}

	contentTypes := []string{
		"text/html; charset=utf-8", "text/html", "application/json",
		"text/html; charset=UTF-8", "application/xhtml+xml",
	}

	techStacks := [][]string{
		{"nginx", "PHP", "MySQL"},
		{"Apache", "Python", "PostgreSQL"},
		{"nginx", "Node.js", "MongoDB"},
		{"cloudflare", "React", "GraphQL"},
		{"nginx", "Vue.js", "Redis"},
		{"Apache", "Java", "Oracle"},
		{"nginx", "Go", "PostgreSQL"},
		{"cloudflare", "Next.js", "Vercel"},
		{"nginx", "Django", "PostgreSQL"},
		{"Apache", "Laravel", "MySQL"},
		{"nginx", "Express", "MongoDB"},
		{"cloudflare", "Angular", "Firebase"},
	}

	statusCodes := []int{200, 200, 200, 200, 200, 301, 302, 403, 404, 500}

	createdCount := 0

	// Each target gets exactly websitesPerTarget websites
	for targetIdx, target := range targets {
		for i := 0; i < websitesPerTarget; i++ {
			// Generate URL based on target type
			var url string
			protocol := protocols[i%len(protocols)]
			subdomain := subdomains[i%len(subdomains)]
			port := ports[i%len(ports)]
			path := paths[i%len(paths)]

			switch target.Type {
			case "domain":
				url = fmt.Sprintf("%s%s.%s%s%s", protocol, subdomain, target.Name, port, path)
			case "ip":
				url = fmt.Sprintf("%s%s%s%s", protocol, target.Name, port, path)
			case "cidr":
				// Generate IP within CIDR range (simplified: use base IP)
				baseIP := target.Name[:len(target.Name)-3] // Remove /XX
				url = fmt.Sprintf("%s%s%s%s", protocol, baseIP, port, path)
			default:
				url = fmt.Sprintf("%s%s.target%d-site%d.com%s%s", protocol, subdomain, targetIdx, i, port, path)
			}

			// Extract host from URL
			host := extractHost(url)

			// Deterministic but varied values
			statusCode := statusCodes[i%len(statusCodes)]
			contentLength := 1000 + (i * 100)
			tech := pq.StringArray(techStacks[i%len(techStacks)])
			vhost := i%5 == 0 // 20% are vhost

			website := &model.Website{
				TargetID:      target.ID,
				URL:           url,
				Host:          host,
				Title:         titles[i%len(titles)],
				StatusCode:    &statusCode,
				ContentLength: &contentLength,
				ContentType:   contentTypes[i%len(contentTypes)],
				Webserver:     webservers[i%len(webservers)],
				Tech:          tech,
				Vhost:         &vhost,
				Location:      "",
				CreatedAt:     time.Now().AddDate(0, 0, -i),
			}

			if err := db.Create(website).Error; err != nil {
				continue
			}
			createdCount++
		}
	}

	fmt.Printf("   ✓ Created %d websites\n", createdCount)
	return nil
}

func extractHost(rawURL string) string {
	// Simple host extraction
	url := rawURL
	// Remove protocol
	if idx := len("https://"); len(url) > idx && url[:idx] == "https://" {
		url = url[idx:]
	} else if idx := len("http://"); len(url) > idx && url[:idx] == "http://" {
		url = url[idx:]
	}
	// Remove path
	if idx := findIndex(url, "/"); idx != -1 {
		url = url[:idx]
	}
	return url
}

func findIndex(s string, substr string) int {
	for i := 0; i < len(s); i++ {
		if s[i] == substr[0] {
			return i
		}
	}
	return -1
}

func createSubdomains(db *gorm.DB, targets []model.Target, subdomainsPerTarget int) error {
	// Only create subdomains for domain-type targets
	domainTargets := make([]model.Target, 0)
	for _, t := range targets {
		if t.Type == "domain" {
			domainTargets = append(domainTargets, t)
		}
	}

	totalCount := len(domainTargets) * subdomainsPerTarget
	fmt.Printf("📝 Creating %d subdomains (%d per domain target, %d domain targets)...\n",
		totalCount, subdomainsPerTarget, len(domainTargets))

	if len(domainTargets) == 0 {
		fmt.Println("   ⚠ No domain targets found, skipping subdomains")
		return nil
	}

	// Subdomain prefixes
	prefixes := []string{
		"www", "api", "app", "admin", "portal", "dashboard", "dev", "staging",
		"test", "cdn", "static", "assets", "mail", "blog", "docs", "support",
		"auth", "login", "shop", "store",
	}

	createdCount := 0

	for _, target := range domainTargets {
		for i := 0; i < subdomainsPerTarget; i++ {
			prefix := prefixes[i%len(prefixes)]
			name := fmt.Sprintf("%s.%s", prefix, target.Name)

			subdomain := &model.Subdomain{
				TargetID:  target.ID,
				Name:      name,
				CreatedAt: time.Now().AddDate(0, 0, -i),
			}

			if err := db.Create(subdomain).Error; err != nil {
				continue
			}
			createdCount++
		}
	}

	fmt.Printf("   ✓ Created %d subdomains\n", createdCount)
	return nil
}

func createEndpoints(db *gorm.DB, targets []model.Target, endpointsPerTarget int) error {
	totalCount := len(targets) * endpointsPerTarget
	fmt.Printf("🔗 Creating %d endpoints (%d per target)...\n", totalCount, endpointsPerTarget)

	if len(targets) == 0 {
		return nil
	}

	// Endpoint data templates
	protocols := []string{"https://", "http://"}
	subdomains := []string{"www", "api", "app", "admin", "portal", "dashboard", "dev", "staging", "test", "cdn"}
	paths := []string{
		"/api/v1/users", "/api/v1/products", "/api/v2/orders", "/login", "/dashboard",
		"/admin/settings", "/app/config", "/docs/api", "/health", "/metrics",
		"/api/auth/login", "/api/auth/logout", "/api/data/export", "/api/search",
		"/graphql", "/ws/connect", "/api/upload", "/api/download", "/status", "/version",
	}

	titles := []string{
		"API Endpoint", "User Service", "Product API", "Authentication",
		"Dashboard API", "Admin Panel", "Configuration", "Documentation",
		"Health Check", "Metrics Endpoint", "GraphQL API", "WebSocket",
	}

	webservers := []string{"nginx/1.24.0", "Apache/2.4.57", "cloudflare", "nginx", "Apache"}
	contentTypes := []string{"application/json", "text/html", "application/xml", "text/plain"}
	techStacks := [][]string{
		{"nginx", "Node.js", "Express"},
		{"Apache", "Python", "FastAPI"},
		{"nginx", "Go", "Gin"},
		{"cloudflare", "Rust", "Actix"},
	}
	gfPatterns := [][]string{
		{"debug-pages", "potential-takeover"},
		{"cors", "ssrf"},
		{"sqli", "xss"},
		{"lfi", "rce"},
		{},
	}
	statusCodes := []int{200, 200, 200, 201, 301, 400, 401, 403, 404, 500}

	createdCount := 0

	for _, target := range targets {
		for i := 0; i < endpointsPerTarget; i++ {
			var url string
			protocol := protocols[i%len(protocols)]
			subdomain := subdomains[i%len(subdomains)]
			path := paths[i%len(paths)]

			switch target.Type {
			case "domain":
				url = fmt.Sprintf("%s%s.%s%s", protocol, subdomain, target.Name, path)
			case "ip":
				url = fmt.Sprintf("%s%s%s", protocol, target.Name, path)
			case "cidr":
				baseIP := target.Name[:len(target.Name)-3]
				url = fmt.Sprintf("%s%s%s", protocol, baseIP, path)
			default:
				continue
			}

			host := extractHost(url)
			statusCode := statusCodes[i%len(statusCodes)]
			contentLength := 500 + (i * 50)
			tech := pq.StringArray(techStacks[i%len(techStacks)])
			matchedGF := pq.StringArray(gfPatterns[i%len(gfPatterns)])
			vhost := i%10 == 0

			endpoint := &model.Endpoint{
				TargetID:          target.ID,
				URL:               url,
				Host:              host,
				Title:             titles[i%len(titles)],
				StatusCode:        &statusCode,
				ContentLength:     &contentLength,
				ContentType:       contentTypes[i%len(contentTypes)],
				Webserver:         webservers[i%len(webservers)],
				Tech:              tech,
				MatchedGFPatterns: matchedGF,
				Vhost:             &vhost,
				CreatedAt:         time.Now().AddDate(0, 0, -i),
			}

			if err := db.Create(endpoint).Error; err != nil {
				continue
			}
			createdCount++
		}
	}

	fmt.Printf("   ✓ Created %d endpoints\n", createdCount)
	return nil
}

func createDirectories(db *gorm.DB, targets []model.Target, directoriesPerTarget int) error {
	totalCount := len(targets) * directoriesPerTarget
	fmt.Printf("📁 Creating %d directories (%d per target)...\n", totalCount, directoriesPerTarget)

	if len(targets) == 0 {
		return nil
	}

	// Directory data templates
	protocols := []string{"https://", "http://"}
	subdomains := []string{"www", "api", "app", "admin", "portal", "dashboard", "dev", "staging", "test", "cdn"}
	directories := []string{
		"/admin/", "/backup/", "/config/", "/data/", "/debug/",
		"/files/", "/images/", "/js/", "/css/", "/uploads/",
		"/api/", "/docs/", "/logs/", "/temp/", "/cache/",
		"/static/", "/assets/", "/media/", "/public/", "/private/",
	}

	contentTypes := []string{"text/html", "application/json", "text/plain", "application/xml"}
	statusCodes := []int{200, 200, 200, 301, 302, 403, 404}

	createdCount := 0

	for _, target := range targets {
		for i := 0; i < directoriesPerTarget; i++ {
			var url string
			protocol := protocols[i%len(protocols)]
			subdomain := subdomains[i%len(subdomains)]
			dir := directories[i%len(directories)]

			switch target.Type {
			case "domain":
				url = fmt.Sprintf("%s%s.%s%s", protocol, subdomain, target.Name, dir)
			case "ip":
				url = fmt.Sprintf("%s%s%s", protocol, target.Name, dir)
			case "cidr":
				baseIP := target.Name[:len(target.Name)-3]
				url = fmt.Sprintf("%s%s%s", protocol, baseIP, dir)
			default:
				continue
			}

			status := statusCodes[i%len(statusCodes)]
			contentLength := int64(1000 + (i * 100))
			duration := int64(50 + (i * 5))

			directory := &model.Directory{
				TargetID:      target.ID,
				URL:           url,
				Status:        &status,
				ContentLength: &contentLength,
				ContentType:   contentTypes[i%len(contentTypes)],
				Duration:      &duration,
				CreatedAt:     time.Now().AddDate(0, 0, -i),
			}

			if err := db.Create(directory).Error; err != nil {
				continue
			}
			createdCount++
		}
	}

	fmt.Printf("   ✓ Created %d directories\n", createdCount)
	return nil
}

func createHostPortMappings(db *gorm.DB, targets []model.Target, mappingsPerTarget int) error {
	// Increase mappings to ensure pagination (100 per target = more IPs)
	actualMappingsPerTarget := mappingsPerTarget * 5 // 20 * 5 = 100 mappings per target
	totalCount := len(targets) * actualMappingsPerTarget
	fmt.Printf("🔌 Creating %d host port mappings (%d per target)...\n", totalCount, actualMappingsPerTarget)

	if len(targets) == 0 {
		return nil
	}

	// Common ports
	ports := []int{22, 80, 443, 8080, 8443, 3000, 3306, 5432, 6379, 27017, 9200, 9300, 5000, 8000, 8888, 9000, 9090, 10000, 11211, 25}

	// Subdomain prefixes for hosts
	subdomains := []string{"www", "api", "app", "admin", "portal", "dashboard", "dev", "staging", "test", "cdn", "mail", "ftp", "db", "cache", "search", "auth", "login", "shop", "store", "blog"}

	createdCount := 0

	for _, target := range targets {
		// Generate base IP for this target
		baseIP1 := rand.Intn(223) + 1
		baseIP2 := rand.Intn(256)
		baseIP3 := rand.Intn(256)

		// Generate more unique IPs per target (10-15 IPs with 6-10 ports each)
		numIPs := 10 + rand.Intn(6) // 10-15 unique IPs
		portsPerIP := actualMappingsPerTarget / numIPs

		for ipIdx := 0; ipIdx < numIPs; ipIdx++ {
			// Generate unique IP
			ip := fmt.Sprintf("%d.%d.%d.%d", baseIP1, baseIP2, baseIP3, ipIdx+1)

			// Generate multiple hosts for this IP
			numHosts := 3 + rand.Intn(4) // 3-6 hosts per IP

			for hostIdx := 0; hostIdx < numHosts; hostIdx++ {
				var host string

				// Generate host based on target type
				switch target.Type {
				case "domain":
					subdomain := subdomains[(ipIdx*numHosts+hostIdx)%len(subdomains)]
					host = fmt.Sprintf("%s.%s", subdomain, target.Name)
				case "ip":
					host = target.Name
				case "cidr":
					baseIP := target.Name[:len(target.Name)-3]
					host = baseIP
				default:
					continue
				}

				// Generate multiple ports for this host-IP combination
				numPorts := portsPerIP / numHosts
				if numPorts < 1 {
					numPorts = 1
				}

				for portIdx := 0; portIdx < numPorts; portIdx++ {
					port := ports[(ipIdx*numHosts*numPorts+hostIdx*numPorts+portIdx)%len(ports)]

					mapping := &model.HostPortMapping{
						TargetID:  target.ID,
						Host:      host,
						IP:        ip,
						Port:      port,
						CreatedAt: time.Now().AddDate(0, 0, -(ipIdx*numHosts*numPorts + hostIdx*numPorts + portIdx)),
					}

					if err := db.Create(mapping).Error; err != nil {
						// Ignore duplicate key errors
						continue
					}
					createdCount++
				}
			}
		}
	}

	fmt.Printf("   ✓ Created %d host port mappings\n", createdCount)
	return nil
}

func createScreenshots(db *gorm.DB, targets []model.Target, screenshotsPerTarget int) error {
	// Screenshots are typically generated by scanners with actual WebP image data
	// For seed data, we create empty records (no image data) to demonstrate the structure
	// In production, scanners would populate the image field with actual WebP binary data

	if screenshotsPerTarget == 0 {
		fmt.Println("📸 Skipping screenshots (typically generated by scanners)")
		return nil
	}

	totalCount := len(targets) * screenshotsPerTarget
	fmt.Printf("📸 Creating %d screenshots (%d per target)...\n", totalCount, screenshotsPerTarget)

	if len(targets) == 0 {
		return nil
	}

	// Screenshot data templates
	protocols := []string{"https://", "http://"}
	subdomains := []string{"www", "api", "app", "admin", "portal", "dashboard", "dev", "staging", "test", "cdn"}
	paths := []string{"", "/", "/login", "/dashboard", "/admin", "/app", "/docs", "/api"}
	statusCodes := []int{200, 200, 200, 200, 301, 302, 403, 404}

	createdCount := 0

	for _, target := range targets {
		for i := 0; i < screenshotsPerTarget; i++ {
			var url string
			protocol := protocols[i%len(protocols)]
			subdomain := subdomains[i%len(subdomains)]
			path := paths[i%len(paths)]

			switch target.Type {
			case "domain":
				url = fmt.Sprintf("%s%s.%s%s", protocol, subdomain, target.Name, path)
			case "ip":
				url = fmt.Sprintf("%s%s%s", protocol, target.Name, path)
			case "cidr":
				baseIP := target.Name[:len(target.Name)-3]
				url = fmt.Sprintf("%s%s%s", protocol, baseIP, path)
			default:
				continue
			}

			statusCode := int16(statusCodes[i%len(statusCodes)])

			screenshot := &model.Screenshot{
				TargetID:   target.ID,
				URL:        url,
				StatusCode: &statusCode,
				Image:      nil, // No actual image data in seed data
				CreatedAt:  time.Now().AddDate(0, 0, -i),
			}

			if err := db.Create(screenshot).Error; err != nil {
				continue
			}
			createdCount++
		}
	}

	fmt.Printf("   ✓ Created %d screenshots (without image data)\n", createdCount)
	return nil
}
